- symbol: "BTC-USD"
  active: true
  data_folder: "bitcoin"
  asset_type: "crypto"
  description: "Bitcoin historical price data"
  column_to_use: "close"
- symbol: "ETH-USD"
  active: true
  data_folder: "ethereum"
  asset_type: "crypto"
  description: "Ethereum historical price data"
  column_to_use: "close"
- symbol: "EURUSD=X"
  active: true
  data_folder: "eur_usd"
  asset_type: "forex"
  description: "Euro historical price data"
  column_to_use: "close"
- symbol: "^GSPC"
  active: true
  data_folder: "sp500"
  asset_type: "index"
  description: "S&P 500 historical price data"
  column_to_use: "close"
- symbol: "^IXIC"
  active: true
  data_folder: "nasdaq"
  asset_type: "index"
  description: "NASDAQ historical price data"
  column_to_use: "close"
- symbol: "GC=F"
  active: true
  data_folder: "gold"
  asset_type: "commodity"
  description: "Gold historical price data"
  column_to_use: "close"